version = 3.10.4
runner.dialect = scala3
maxColumn = 120
rewrite.rules = [Imports, AvoidInfix, SortModifiers, ExpandImportSelectors]
rewrite.imports {
  sort = ascii
  contiguousGroups = "no"
  groups = [[".*"]]
}
assumeStandardLibraryStripMargin = true
project.excludeFilters = []
project.layout = StandardConvention
newlines.topLevelStatementBlankLines = [
  { maxNest = 0, blanks = 1, regex = "Import" }
]
rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.newSyntax.control = false
