name: Scala

on:
  pull_request:
    paths:
      - '.github/workflows/test-scala.yml'
      - 'scala/src/**'
      - 'scala/build.sbt'
      - 'scala/project/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    timeout-minutes: 5
    defaults:
      run:
        working-directory: scala
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: temurin
          java-version: '21'
          cache: sbt
      - uses: sbt/setup-sbt@af116cce31c00823d3903ce687f9cda3a4f19f1b # v1
      - run: sbt compile
      - run: sbt "testOnly folio.codinginterview.OptimalPortfolioScenario"
